### ISSUE TITLE
avoir une recherche multicritères

### ISSUE THREAD

**Issue by atm-berengere** [ATM-Consulting/dolibarr_module_searcheverywhere#8]

**Comment by atm-alexis** [comment]
Re, il va nous falloir un peu plus d'infos sur ce que tu appelles une recherche multicritère (dans la mesure où s'en est déjà une). Peux-tu nous préciser le besoin,

Merci

**Comment by atm-berengere** [comment]
multicritère dans la recherche pas dans les résultats :+1: 
si je cherche le produit chaise + atm (sur la démo), c'est une recherche avec plusieurs "mots clefs", résultat de recherche = 0 ; alors que j'ai bien une propale au nom d'atm  avec un produit chaise.
en gros c'est une recherche affiner en fonction de plusieurs critères/mots clefs

**Comment by atm-florianm** [comment]
Je ferme l'issue car pas une évolution envisagée à l'heure actuelle.
